for文(アプリ編)編集
AsukaKanematsu/for-php pull request #1
Opened 2023-04-13 12:57 UTC by AsukaKanematsu

2023-04-14 08:05 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙋😊

2023-04-14 08:05 UTC, KatsuyaTanaka95 commented on src/public/calculation.php
> +$peopleNum = 7;
こちらの変更では課題の指示通りになっていなそうです😭
ご修正をお願いいたします！😊

https://user-images.githubusercontent.com/63081802/231983072-52ddd775-1fee-43ca-b577-0827746da778.mov

2023-04-17 12:23 UTC, AsukaKanematsu commented
[PHP基礎] for文(アプリ編)

### 詳細作業
1~[入力値に+7した値]の和を求める機能に変更しましょう。
$pyramidStepNum += 7;　を付け足しました。
![2023-04-17](https://user-images.githubusercontent.com/129743465/232482523-75a1709d-4126-495a-9852-cc6dccd28f96.png)

2023-04-18 01:03 UTC, KatsuyaTanaka95 approved these changes
昨日もお疲れ様でした！
ご修正ありがとうございます！
mergeいただけると助かります！🙆🙋😊

2023-04-18 14:32 UTC, merged